repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: check-version-match
        name: Check VERSION matches pyproject.toml
        entry: python scripts/check_version.py
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest
        entry: pytest
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: run-coverage
        name: Run coverage and report
        entry: coverage run -m pytest && coverage report --fail-under=80
        language: system
        types: [python]
