repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2  # updated to a compatible Ruff version for format support
    hooks:
      - id: ruff
        name: Ruff Linter (auto-fix)
        args: ["--fix"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff Formatter
        entry: ruff format
        language: system
        types: [python]

      - id: test-with-coverage
        name: Run tests with coverage enforcement
        entry: bash -c 'coverage run -m pytest && coverage report --fail-under=72'
        language: system
        types: [python]
