[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "filetools"
version = "0.0.0" # Placeholder for the dynamic version
authors = [
  { name="James Berkheimer", email="james.berkheimer@gmail.com" },
]
description = "A set of tools to help parse downloaded media files"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
filetools = "filetools.main:main"

[project.urls]
"Homepage" = "https://github.com/james-berkheimer/jb-filetools"
"Bug Tracker" = "https://github.com/james-berkheimer/jb-filetools/issues"

[tool.hatch.version]
path = "VERSION"
