# Basic configuration
line-length = 105
indent-width = 4
target-version = "py312"
fix = true
unsafe-fixes = true

# Exclude commonly ignored directories
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "vendor",
    "generated",
    "_redunant/",
    "filetools/_scratch.py",
]


[lint]
select = [
    "B",   # flake8-bugbear
    "C",   # mccabe complexity
    "E",   # pycodestyle errors
    "F",   # Pyflakes
    "N",   # PEP8 naming
    "W",   # pycodestyle warnings
    "B9",  # flake8-bugbear additional rules
    "I",   # isort
    "ISC", # flake8-implicit-str-concat
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ANN", # flake8-annotations
    "Q",   # flake8-quotes
    "S",   # flake8-bandit security rules
    # "D",   # pydocstyle
    "RET", # flake8-return
    "A",   # flake8-builtins
]

# Ignore rules
ignore = [
    "E203",   # Whitespace before ':'
    "E501",   # Line too long
    "E722",   # Bare except
    "N802",   # Function name should be lowercase
    "F401",   # Unused imports
    "ISC001", # Implicit string concatenation
    "E721",   # Type comparison using type()
    "D100",   # Missing docstring in public module
    "D104",   # Missing docstring in public package
    "S101",   # Use of assert detected
    "F841",   # Local variable is assigned to but never used
]

# Fix settings
fixable = ["ALL"]
unfixable = ["Q000", "F401"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Per-file ignore settings
[lint.per-file-ignores]
"tests/*" = ["S101", "ANN", "D"]
"__init__.py" = ["F401"]
"examples/*" = ["D", "ANN"]

[lint.pydocstyle]
convention = "google"

[lint.mccabe]
max-complexity = 10

[lint.isort]
known-first-party = ["jb_filetools"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
combine-as-imports = true

[lint.flake8-annotations]
mypy-init-return = true
suppress-none-returning = false

[lint.pycodestyle]
max-doc-length = 120

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = true
docstring-code-line-length = 80
