[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "filetools"
version = "1.0.0"
authors = [
  { name="James Berkheimer", email="james.berkheimer@gmail.com" },
]
description = "A set of tools to help parse downloaded media files"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/james-berkheimer/jb-filetools"
"Bug Tracker" = "https://github.com/james-berkheimer/jb-filetools/issues"