name: Release Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js (for semantic-release)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run semantic-release to determine version and create release
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # Update FILETOOLS_VERSION in env-template
      - name: Update FILETOOLS_VERSION in env-template
        run: |
          # Parse the new version from semantic-release output
          NEW_VERSION=$(npx semantic-release --dry-run | grep 'nextRelease.version' | cut -d '"' -f4)
          echo "Updating FILETOOLS_VERSION to $NEW_VERSION in env-template"

          # Update the FILETOOLS_VERSION in env-template
          sed -i "s/^FILETOOLS_VERSION=.*/FILETOOLS_VERSION=${NEW_VERSION}/" deployment/lxc/env-template

      # Commit the updated env-template
      - name: Commit updated env-template
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add deployment/lxc/env-template
          git commit -m "ci: update FILETOOLS_VERSION to ${NEW_VERSION}"
          git push origin main
